# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
publish = "public"
command = "npm run build:preview"

[context.production]
command = "npm run build:production"

[build.environment]
GO_VERSION = "1.20.5"
